### ISSUE TITLE
KeyError: 'LevelOfDetail'

### ISSUE THREAD

**Issue by yathatguy** [cdump/investments#1]
OS: MacOs Catalina
Python: 3.7.6

```
❯ /System/Volumes/Data/Users/thatguy/Library/Python/3.7/bin/ibtax --activity-reports-dir "/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019" --confirmation-reports-dir "/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019"
[*] Activity report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/U2790801_2019_2019.csv
[*] Activity report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/Trade_Confirmation.csv
[*] Confirmation report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/U2790801_2019_2019.csv
[*] Confirmation report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/Trade_Confirmation.csv
================================================================

Traceback (most recent call last):
  File "/System/Volumes/Data/Users/thatguy/Library/Python/3.7/bin/ibtax", line 8, in <module>
    sys.exit(main())
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/ibtax/ibtax.py", line 115, in main
    trade_confirmation_csvs=confirmation_reports,
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 102, in parse_csv
    self._parse_trade_confirmation_csv(csv.reader(tc_fh, delimiter=','))
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 128, in _parse_trade_confirmation_csv
    if f['LevelOfDetail'] != 'EXECUTION':
KeyError: 'LevelOfDetail'
```

**Comment by cdump** [comment]
@yathatguy выглядит так, что **Trade Confirmation** криво экспортировалось. Вы все делали по инструкции https://github.com/cdump/investments#trade-confirmation ?
Если да, скиньте первую сторочку csv (заголовок) из Trade_Confirmation.csv

**Comment by yathatguy** [comment]
Да, шел по инструкции. Первая строчка из файла:

```
"ClientAccountID","AccountAlias","Model","CurrencyPrimary","AssetClass","Symbol","Description","Conid","SecurityID","SecurityIDType","CUSIP","ISIN","ListingExchange","UnderlyingConid","UnderlyingSymbol","UnderlyingSecurityID","UnderlyingListingExchange","Issuer","Multiplier","Strike","Expiry","Put/Call","PrincipalAdjustFactor","TransactionType","TradeID","OrderID","ExecID","BrokerageOrderID","OrderReference","VolatilityOrderLink","ClearingFirmID","OrigTradePrice","OrigTradeDate","OrigTradeID","OrderTime","Date/Time","ReportDate","SettleDate","TradeDate","Exchange","Buy/Sell","Quantity","Price","Amount","Proceeds","Commission","BrokerExecutionCommission","BrokerClearingCommission","ThirdPartyExecutionCommission","ThirdPartyClearingCommission","ThirdPartyRegulatoryCommission","OtherCommission","CommissionCurrency","Tax","Code","OrderType","LevelOfDetail","TraderID","IsAPIOrder","AllocatedTo","AccruedInterest","RFQID"
```

**Comment by cdump** [comment]
Проблема в том, что вы положили оба отчета в одну и ту же директорию и парсер TradeConfirmation попытался спарсить отчет Activity.
Положите отчеты в разные директории и все должно будет заработать.
Я подумаю как лучше проверить такое в коде или подробнее опишу этот момент в доках.

**Comment by yathatguy** [comment]
да, так отрабатывает

**Comment by cdump** [comment]
Добавил в README + проверку внутри ibtax
