### ISSUE TITLE
Exception: dividend not found for XXX при перевыгрузке отчета

### ISSUE THREAD

**Issue by cdump** [cdump/investments#17]
Перевыгрузил отчет activity за 2016 год и получил следующую ошибку:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/devel/invest/investments/ibtax/ibtax.py", line 133, in main
    p.parse_csv(
  File "/home/user/devel/invest/investments/report_parsers/ib.py", line 129, in parse_csv
    self._real_parse_activity_csv(csv.reader(activity_fh, delimiter=','), {
  File "/home/user/devel/invest/investments/report_parsers/ib.py", line 180, in _real_parse_activity_csv
    parser_fn(fields)
  File "/home/user/devel/invest/investments/report_parsers/ib.py", line 250, in _parse_withholding_tax
    raise Exception(f'dividend not found for {ticker} on {date}')
Exception: dividend not found for HPQ (Stock) on 2017-01-04
```

Отчет за 2016 год, который выгружал в 2019 году:
```
Statement,Data,WhenGenerated,"2019-03-09, 03:43:46 EST"
Dividends,Data,USD,2016-06-01,INTC (US4581401001) Cash Dividend USD 0.26000000 (Ordinary Dividend),6.5                                                                                                                   
Withholding Tax,Data,USD,2016-06-01,INTC (US4581401001) Cash Dividend USD 0.26000000 - US Tax,-0.65, 
```

Отчет за 2016 год, который выгрузил в 2020 году:
```
Statement,Data,WhenGenerated,"2020-10-02, 01:59:30 EDT"                                              
Dividends,Data,USD,2016-06-01,INTC (US4581401001) Cash Dividend USD 0.26000000 (Ordinary Dividend),6.5                                                                                                                   
Withholding Tax,Data,USD,2016-06-01,INTC(US4581401001) Choice Dividend  0.26000000 USD Distribution Value - US Tax,-0.65,
```

Пока выглядит как баг на стороне отчетов IB, но надо поддержать оба случая

**Comment by qk4l** [comment]
Это скорее не баг, а последующие коррекции налогов.
Нужно обрабатывать, думаю правильнее всего учитывать их для последнего выплаченного дивидента.
