### ISSUE TITLE
No support for Forex orders

### ISSUE THREAD

**Issue by yathatguy** [cdump/investments#2]
```
❯ /System/Volumes/Data/Users/thatguy/Library/Python/3.7/bin/ibtax --activity-reports-dir "/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019" --confirmation-reports-dir "/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/1"
[*] Activity report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/U2790801_2019_2019.csv
[*] Confirmation report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/1/Trade_Confirmation.csv
================================================================

Traceback (most recent call last):
  File "/System/Volumes/Data/Users/thatguy/Library/Python/3.7/bin/ibtax", line 8, in <module>
    sys.exit(main())
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/ibtax/ibtax.py", line 115, in main
    trade_confirmation_csvs=confirmation_reports,
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 111, in parse_csv
    'Deposits & Withdrawals': self._parse_deposits,
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 157, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 170, in _parse_trades
    ticker = self._tickers.get_ticker(f['Symbol'], _parse_tickerkind(f['Asset Category']))
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 25, in _parse_tickerkind
    raise ValueError(strval)
ValueError: Forex
```

**Comment by cdump** [comment]
Можно попробовать в _/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/ticker.py_ дописать

```
class TickerKind(Enum):
    Stock = 1
    Option = 2
    Futures = 3
    Bond = 4
    Forex = 5
```
а в _/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py_ поправить 
```
def _parse_tickerkind(strval: str):
    if strval == 'Stocks':
        return TickerKind.Stock
    if strval == 'Equity and Index Options':
        return TickerKind.Option
    if strval == 'Forex':
        return TickerKind.Forex
    raise ValueError(strval)
```

Или можете прислать "обезличенный" activity отчет, оставив там только информацию связанную с Forex (суммы можно изменить) - я посмотрю и попробую поправить

**Comment by yathatguy** [comment]
```
❯ /System/Volumes/Data/Users/thatguy/Library/Python/3.7/bin/ibtax --activity-reports-dir "/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019" --confirmation-reports-dir "/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/1"
[*] Activity report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/U2790801_2019_2019.csv
[*] Confirmation report /Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/1/Trade_Confirmation.csv
================================================================

Traceback (most recent call last):
  File "/System/Volumes/Data/Users/thatguy/Library/Python/3.7/bin/ibtax", line 8, in <module>
    sys.exit(main())
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/ibtax/ibtax.py", line 115, in main
    trade_confirmation_csvs=confirmation_reports,
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 113, in parse_csv
    'Deposits & Withdrawals': self._parse_deposits,
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 159, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 172, in _parse_trades
    ticker = self._tickers.get_ticker(f['Symbol'], _parse_tickerkind(f['Asset Category']))
  File "/Users/thatguy/Library/Python/3.7/lib/python/site-packages/investments/report_parsers/ib.py", line 70, in get_ticker
    raise KeyError
KeyError
```

вилимо, не везде поправили

**Comment by cdump** [comment]
Можете скинуть `grep 'Financial Instrument Information' '/Users/thatguy/Yandex.Disk.localized/Финансы/Interactive Brokers/2019/U2790801_2019_2019.csv'`? Можно оставить только строки с Forex

У меня в отчетах не было сделок с Forex, сложно "в слепую" править :(

**Comment by cdump** [comment]
Временно добавил пропуск Forex и warning про это + добавил это в список неподдерживаемых фичей в readme, которые возможно будут исправлены потом.
В версии 0.1.8 должно парситься без падений
