### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Lokkenum** [cdump/investments#3]
Ubuntu 18.04.4 LTS
Python 3.6.9

```
root@linux:~/investments-master/investments/ibtax# poetry run ibtax.py --activity-reports-dir "/home/croot/ACT/" --confirmation-reports-dir "/home/croot/TC/"
The currently activated Python version 2.7.17 is not supported by the project (^3.6.1 || ^3.7).
Trying to find and use a compatible version. 
Using python3 (3.6.9)
[*] Activity report /home/croot/ACT/2018.csv
[*] Activity report /home/croot/ACT/2020.csv
[*] Activity report /home/croot/ACT/2019.csv
[*] Confirmation report /home/croot/TC/TC2018.csv
[*] Confirmation report /home/croot/TC/TC2020.csv
[*] Confirmation report /home/croot/TC/TC2019.csv
================================================================

Traceback (most recent call last):
  File "/home/croot/.cache/pypoetry/virtualenvs/investments-yjvgpkFm-py3.6/bin/ibtax", line 11, in <module>
    load_entry_point('investments', 'console_scripts', 'ibtax')()
  File "/home/croot/investments-master/investments/ibtax/ibtax.py", line 115, in main
    trade_confirmation_csvs=confirmation_reports,
  File "/home/croot/investments-master/investments/report_parsers/ib.py", line 96, in parse_csv
    'Financial Instrument Information': self._parse_instrument_information,
  File "/home/croot/investments-master/investments/report_parsers/ib.py", line 157, in _real_parse_activity_csv
    parser_fn(fields)
  File "/home/croot/investments-master/investments/report_parsers/ib.py", line 166, in _parse_instrument_information
    multiplier=int(f['Multiplier']),
  File "/home/croot/investments-master/investments/report_parsers/ib.py", line 49, in put
    assert description not in self._description_to_ticker
AssertionError
```

**Comment by cdump** [comment]
Можете скинуть `grep 'Financial Instrument Information' /home/croot/ACT/*`? Можно ограничить вывод до тикеров, у которых одинаковый столбец "Description"

**Comment by Lokkenum** [comment]
Могу скинуть на почту или в hangouts. Куда лучше?
Вероятно ошибка из-за сплита одной акции в одном из годов.
С другой стороны, запустив скрипт только на одном (первом) отчёте, где всё тривиально получаю:

```
poetry run ibtax.py --activity-reports-dir "/home/croot/ACT/" --confirmation-reports-dir "/home/croot/TC/"
The currently activated Python version 2.7.17 is not supported by the project (^3.6.1 || ^3.7).
Trying to find and use a compatible version. 
Using python3 (3.6.9)
[*] Activity report /home/croot/ACT/2018.csv
[*] Confirmation report /home/croot/TC/TC2018.csv
================================================================

Traceback (most recent call last):
  File "/home/croot/.cache/pypoetry/virtualenvs/investments-yjvgpkFm-py3.6/bin/ibtax", line 11, in <module>
    load_entry_point('investments', 'console_scripts', 'ibtax')()
  File "/home/croot/investments-master/investments/ibtax/ibtax.py", line 129, in main
    finished_trades_df = pandas.DataFrame(finished_trades, columns=finished_trades[0]._fields)  # noqa: WPS437
IndexError: list index out of range
```

**Comment by cdump** [comment]
Можно на andreevmaxim@gmail.com или в @cdump в телеграм написать - так думаю даже быстрее получится все отловить и поправить :)

**Comment by Lokkenum** [comment]
Телеграм наше всё! :)

**Comment by cdump** [comment]
Ошибка с `IndexError: list index out of range` поправлена, остались неподдерживаемая обработка сплитов

**Comment by Lokkenum** [comment]
> Ошибка с `IndexError: list index out of range` поправлена, осталась неподдерживаемая обработка сплитов

Проверил на первом годовом отчёте, ошибка с `IndexError: list index out of range` пропала! Спасибо! 
Увидел как выглядит расчёт, теперь думаю как можно его улучшить (а также перевести на русский), добавить Итого по дивидендам, Всего к доплате и т.д.
Предлагаю завтра обсудить в телеграме.

**Comment by cdump** [comment]
Про split сделал отдельный issue - https://github.com/cdump/investments/issues/6
