### ISSUE TITLE
Просьба добавить поддержку валют. В частности CAD

### ISSUE THREAD

**Issue by President** [cdump/investments#39]
Traceback (most recent call last):
  File "/Users/kostya/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kostya/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibdds/__main__.py", line 3, in <module>
    main()
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibdds/ibdds.py", line 86, in main
    parser_object = parse_reports(args.activity_report_filepath)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibdds/ibdds.py", line 39, in parse_reports
    parser_object.parse_csv(activity_report_filepath=activity_report)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibdds/ibdds.py", line 27, in parse_csv
    self._real_parse_activity_csv(csv.reader(activity_fh, delimiter=','), {
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/report_parsers/ib.py", line 211, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/report_parsers/ib.py", line 327, in _parse_cash_report
    currency = Currency.parse(currency_code)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/currency.py", line 17, in parse
    raise ValueError(strval)
ValueError: CAD

**Comment by cdump** [comment]
Только CAD есть в том отчете или другие валюты помимо USD?

**Comment by Rom888** [comment]
Присоединяюсь к просьбе, у меня USD и EUR.
Если нужен пример активити репорта брокера - пришлю куда скажете.

**Comment by esemi** [comment]
@President @Rom888 Коллеги, а можно примерчик отчёта с разными валютами?
Пробую сделать эту фичу

**Comment by Rom888** [comment]
@esemi на какую почту можно прислать пример отчета с разными валютами?

**Comment by esemi** [comment]
> @esemi на какую почту можно прислать пример отчета с разными валютами?

@Rom888 support@esemi.ru
Или можно удалить перс данные и выложить на диск куда?)

**Comment by Rom888** [comment]
@esemi  
отправил на почту, спасибо за внимание к этому issue.

**Comment by esemi** [comment]
Прогнал по живому отчёту тулу. Всё должно работать корректно только с одним ограничением - комиссия и налог по дивам/сделкам должны быть уплачены в валюте операции. Другими словами, если бумага продавалась за одну валюту, а комиссии за эту операцию списали в другой - тула такое не прожуёт и сообщит об этом.

Для дивидендов это не так критично и данную проверку можно убрать, но вот для сделок это сложнее, поскольку комиссии учитываются в цене бумаги при купле/продаже и сейчас разные валюты там не сложить.

Но в целом должно работать, мерж реквест есть, ждём @cdump чтобы проверить да влить в тулу)
