### ISSUE TITLE
KeyError: 'VANGUARD REIT ETF'

### ISSUE THREAD

**Issue by nikzolotov** [cdump/investments#4]
Привет, Максим! Запустил на своих отчётах. Вот что получил:
```
nikzolotov@Nikitas-MacBook-Pro investments % poetry run ibtax --activity-reports-dir "/Users/nikzolotov/Desktop/as/" --confirmation-reports-dir "/Users/nikzolotov/Desktop/flex"
[*] Activity report /Users/nikzolotov/Desktop/as/2020.csv
[*] Activity report /Users/nikzolotov/Desktop/as/2019.csv
[*] Activity report /Users/nikzolotov/Desktop/as/2018.csv
[*] Activity report /Users/nikzolotov/Desktop/as/2017.csv
[*] Confirmation report /Users/nikzolotov/Desktop/flex/2020.csv
[*] Confirmation report /Users/nikzolotov/Desktop/flex/2019.csv
[*] Confirmation report /Users/nikzolotov/Desktop/flex/2018.csv
[*] Confirmation report /Users/nikzolotov/Desktop/flex/2017.csv
================================================================

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nikzolotov/Desktop/investments/investments/ibtax/ibtax.py", line 125, in main
    trade_confirmation_csvs=confirmation_reports,
  File "/Users/nikzolotov/Desktop/investments/investments/report_parsers/ib.py", line 107, in parse_csv
    'Financial Instrument Information': self._parse_instrument_information,
  File "/Users/nikzolotov/Desktop/investments/investments/report_parsers/ib.py", line 168, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/nikzolotov/Desktop/investments/investments/report_parsers/ib.py", line 177, in _parse_instrument_information
    multiplier=int(f['Multiplier']),
  File "/Users/nikzolotov/Desktop/investments/investments/report_parsers/ib.py", line 66, in put
    assert self._description_to_ticker[description] == ticker
KeyError: 'VANGUARD REIT ETF'
```

**Comment by cdump** [comment]
Привет!
Можешь скинуть
`$ grep -R 'Financial Instrument Information' /Users/nikzolotov/Desktop/as/|grep 'VANGUARD'`
?
Почему-то для одного из тикеров изменился description

**Comment by cdump** [comment]
Эта ошибка исправлена в master
