### ISSUE TITLE
Генерация НДФЛ3 не работает  - assert conid not in self._conid_to_ticker

### ISSUE THREAD

**Issue by President** [cdump/investments#40]
% python3 -m investments.ibtax --activity-reports-dir ./activity --confirmation-reports-dir ./confirmation
Traceback (most recent call last):
  File "/Users/kostya/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kostya/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibtax/__main__.py", line 3, in <module>
    main()
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibtax/ibtax.py", line 251, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/ibtax/ibtax.py", line 226, in parse_reports
    parser_object.parse_csv(
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/report_parsers/ib.py", line 142, in parse_csv
    self._real_parse_activity_csv(csv.reader(ac_fh, delimiter=','), {
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/report_parsers/ib.py", line 211, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/report_parsers/ib.py", line 216, in _parse_instrument_information
    self._tickers.put(
  File "/Users/kostya/.local/lib/python3.9/site-packages/investments/report_parsers/ib.py", line 65, in put
    assert conid not in self._conid_to_ticker
AssertionError

**Comment by cdump** [comment]
Изменился параметр тикера, при этом сам тикер не изменился - надо разобраться подробнее. Можете скинуть вывод команды?
```grep -R 'Financial Instrument Information' ./activity```

**Comment by anton-suprunov** [comment]
У меня что-то похожее, 

```
$ python -m investments.ibtax --activity-reports-dir ./activity/ --confirmation-reports-dir ./tradeconfirmation/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\ibtax\__main__.py", line 3, in <module>
    main()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\ibtax\ibtax.py", line 251, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\ibtax\ibtax.py", line 226, in parse_reports
    parser_object.parse_csv(
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\report_parsers\ib.py", line 154, in parse_csv
    self._real_parse_activity_csv(csv.reader(activity_fh, delimiter=','), {
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\report_parsers\ib.py", line 211, in _real_parse_activity_csv
    parser_fn(fields)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\report_parsers\ib.py", line 230, in _parse_trades
    ticker = self._tickers.get_ticker(f['Symbol'], ticker_kind)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\investments\report_parsers\ib.py", line 94, in get_ticker
    raise KeyError(name)
KeyError: 'AAPL 15JAN21 180.0 C'
```

**Comment by Rizhiy** [comment]
Вот пример:
```
Financial Instrument Information	Data	Stocks	APA	APA CORP	474515500	US03743Q1085	NASDAQ	1	COMMON
Financial Instrument Information	Data	Stocks	APA	APACHE CORP	4472	US0374111054	NASDAQ	1	COMMON
```

**Comment by cdump** [comment]
> Поскольку тикеры могут меняться надо хранить не только название, но и дату.

В отчете есть дата когда параметры тикера изменились?

**Comment by Rizhiy** [comment]
Я не нашел пока

**Comment by Rizhiy** [comment]
В Trade Confirmation есть привязка каждой сделки к правильному активу, так что можно от туда инфу брать.

**Comment by cdump** [comment]
Можно еще мапинг нескольких conid на ticker попробовать, убедившись что другие параметры (multiplier, возможно что-то еще) не изменились
