### ISSUE TITLE
Не поддерживается дробное количество акций

### ISSUE THREAD

**Issue by xkrt** [cdump/investments#52]
Привет!

На примере кейса с KD (спинофф IBM). Я получил в портфель дробное количество акций.

```
$ cat ~/.ibtax/activity-statements/2021.csv | grep KD
Mark-to-Market Performance Summary,Data,Stocks,KD,0,0,--,--,-2.672,0.1,-0.08002695,0,-2.65202695,
Realized & Unrealized Performance Summary,Data,Stocks,KD,0,0,-2.21282695,0,0,-2.21282695,0,0,0,0,0,-2.21282695,
Trades,Data,Order,Stocks,USD,KD,"2021-11-16, 12:30:01",-0.4,19.95,19.7,7.98,-0.080026951,-10.1128,-2.212827,0.1,C;FP
Trades,SubTotal,,Stocks,USD,KD,,-0.4,,,7.98,-0.080026951,-10.1128,-2.212827,0.1,
Corporate Actions,Data,Stocks,USD,2021-11-04,"2021-11-03, 20:25:00","IBM(US4592001014) Spinoff  2 for 10 (KD, KYNDRYL HOLDINGS INC-W/I, US50155Q1004)",0.4,0,0,0,
Financial Instrument Information,Data,Stocks,KD,KYNDRYL HOLDINGS INC,520488080,US50155Q1004,NYSE,1,COMMON,
```

```
$ ibtax --activity-reports-dir ~/.ibtax/activity-statements/ --confirmation-reports-dir ~/.ibtax/trade-confirmation/
Traceback (most recent call last):
  File "/Users/xkrt/Library/Python/3.9/bin/ibtax", line 8, in <module>
    sys.exit(main())
  File "/Users/xkrt/Library/Python/3.9/lib/python/site-packages/investments/ibtax/ibtax.py", line 251, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
  File "/Users/xkrt/Library/Python/3.9/lib/python/site-packages/investments/ibtax/ibtax.py", line 226, in parse_reports
    parser_object.parse_csv(
  File "/Users/xkrt/Library/Python/3.9/lib/python/site-packages/investments/report_parsers/ib.py", line 154, in parse_csv
    self._real_parse_activity_csv(csv.reader(activity_fh, delimiter=','), {
  File "/Users/xkrt/Library/Python/3.9/lib/python/site-packages/investments/report_parsers/ib.py", line 211, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/xkrt/Library/Python/3.9/lib/python/site-packages/investments/report_parsers/ib.py", line 243, in _parse_trades
    quantity=int(f['Quantity']) * quantity_multiplier,
ValueError: invalid literal for int() with base 10: '-0.4'
```

**Comment by cdump** [comment]
https://github.com/cdump/investments/pull/76
