### ISSUE TITLE
Подготовка отчетов - устаревшая инструкция по выгрузке Trade Confirmation отчетов

### ISSUE THREAD

**Issue by markin-io** [cdump/investments#58]
В инструкции по подготовке Trade Confirmation отчетов указано, что необходимо создать Flex Query,  а затем проследовать в Reports / Tax Docs > Custom Statements для генерации отчета. 

Данные элементы в интерфейсе в данный момент изменены/отсутствуют, и в Tax Documents нет "Custom Statement". 

При использовании документа, созданного с помощью Flex Query получаю следующую ошибку:
```
(base) igor@markin-io ibkr_tax % python3 -m investments.ibtax --activity-reports-dir ./activity_reports --confirmation-reports-dir ./confirmation_reports
Traceback (most recent call last):
  File "/Users/igorwork/development/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/igorwork/development/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/ibtax/__main__.py", line 3, in <module>
    main()
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/ibtax/ibtax.py", line 291, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/ibtax/ibtax.py", line 263, in parse_reports
    parser_object.parse_csv(
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/report_parsers/ib.py", line 189, in parse_csv
    self._real_parse_activity_csv(csv.reader(ac_fh, delimiter=','), {
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/report_parsers/ib.py", line 259, in _real_parse_activity_csv
    parser_fn(fields)
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/report_parsers/ib.py", line 264, in _parse_instrument_information
    self._tickers.put(
  File "/Users/igorwork/.local/lib/python3.8/site-packages/investments/report_parsers/ib.py", line 69, in put
    assert conid not in self._conid_to_ticker
AssertionError
```

Необходимо обновить инструкцию в соответствии с новым интерфейсом IBKR.

**Comment by esemi** [comment]
Тебе нужны Reports -> Flex Queries и дальше всё по инструкции

**Comment by markin-io** [comment]
@esemi на данный момент по какой-то причине экспорт CSV для "Statements -> Default Statements -> Trade Confirmation" недоступен. Отсутствует вообще в выпадающем списке.

<img width="800" alt="Screenshot 2022-04-26 at 18 11 51" src="https://user-images.githubusercontent.com/3499359/165319444-9ad3620f-f1b1-4094-b8a8-d7f312306d67.png">

**Comment by esemi** [comment]
@markin-io тут моя ошибка, для trade confirmation документация актуальна: Reports / Tax Docs > Flex Queries > Trade Confirmation Flex Query

**Comment by monitorius** [comment]
Инструкция про Flex Queries на данный момент актуальна, только что проверил, issue можно закрыть
