### ISSUE TITLE
Ошибка в TickersStorage

### ISSUE THREAD

**Issue by RomanS2N** [cdump/investments#62]
Приветствую!

У меня на отчётах за 2022 год, выводит ошибку, подскажите в чём может быть причина или как диагностировать её? замечу что на отчётах за 2021 г. всё работает! 

>python -m investments.ibtax --activity-reports-dir D:\NDFL\Reports\ --confirmation-reports-dir D:\Config\

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\ibtax\__main__.py", line 3, in <module>
    main()
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\ibtax\ibtax.py", line 291, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\ibtax\ibtax.py", line 263, in parse_reports
    parser_object.parse_csv(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\report_parsers\ib.py", line 190, in parse_csv
    self._real_parse_activity_csv(csv.reader(ac_fh, delimiter=','), {
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\report_parsers\ib.py", line 260, in _real_parse_activity_csv
    parser_fn(fields)
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\report_parsers\ib.py", line 265, in _parse_instrument_information
    self._tickers.put(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\report_parsers\ib.py", line 79, in put
    assert self._conid_to_ticker[conid] == ticker
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
Указывает на ошибку conid: KeyError: '589316229' 
========================================
Заранее благодарен за ваш отзыв!

**Comment by RomanS2N** [comment]
Здесь вижу ticker повторно появляется в записи и  if ticker not in self._tickers: не срабатывает. Непонятно, то ли в коде так должно быть, толи в файлах проблема.

**Comment by esemi** [comment]
Привет!

Выглядит как-будто в отчёте что-то странное, может сплит акций эпла был в этом году?

**Comment by RomanS2N** [comment]
Это я к сожалению, не знаю ... Т.е. вы считаете что Conid 589316229 нужно просто заменить 416310868 и это проблему вылечит, без каких либо дополнительных косяков?

**Comment by esemi** [comment]
Я просто предположил, что ошибка похожа на смену идишки тикера эпла и такое может быть если случился сплит акций. Сам эплом не владел, не слежу за ним)

Можете попробовать обезличенный отчёт закинуть сюда, я подебажу интересу ради)

**Comment by RomanS2N** [comment]
Попробую, заменить Conid, может исправиться, чистить это целая работа , а Conid - это что за переменная?

**Comment by RomanS2N** [comment]
В общем, замена не помогла, другую ошибку выкинул: 
`  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\investments\report_parsers\ib.py", line 231, in _parse_trade_confirmation_csv
    if f['LevelOfDetail'] != 'EXECUTION':
       ~^^^^^^^^^^^^^^^^^`

Попытаюсь вырезать некорректный кусок и добавить здесь, а вы можете в свой шаблонный отчёт для дебарга добавить и откатать ...

**Comment by RomanS2N** [comment]
**esemi**, как можно извлечь ошибочные записи из большого массива? Не получается запись с ошибкой вытащить из большого массива данных!

К примеру на такой сделки проблема: 
Financial Instrument Information,Data,Stocks,PT,PINTEC TECHNOLOGY HOLDINGS L,338719507,US72352G1076,NASDAQ,1,ADR,	

Trades,Data,Order,Stocks,USD,PT,"2022-03-10, 10:14:02","11,985",0.5932,0.5801,-7109.502,-59.925,9399.526099,2230.099099,-157.0035,C	P		

конфликтует с записью:
Financial Instrument Information,Data,Stocks,PT,PINTEC TECHNOLOGY HOLDINGS L,559931429,US72352G2066,NASDAQ,1,ADR,	
	
Trades,Data,Order,Stocks,USD,PT,"2022-10-12, 12:42:28","5,900",0.577516593,0.9058,-3407.3479,-29.5,3507.271986,70.424086,1936.8721,C	P		

Разница в conid 338719507 <> 559931429

Хотя может взять один отчёт с одной сделкой и копировать записи в пустой второй с заменой 	conid, так при помощи замены вызвать ошибку при которых в двух файлах разные conid стоять будут! И протестить ...

**Comment by RomanS2N** [comment]
Если есть возможность в ручную подправить, не дожидаясь длинного фикса, буду так же рад!

**Comment by RomanS2N** [comment]
Ребята, если будите фиксить, вот некоторые тикеты которые выдают ошибки:

HOTH Conid 353038807 vs 593821783  2022-01-03 <> 2022-01-06
AVCT   Conid 416310868 vs 589316229  2022-08-28  <> 2022-10-11
PT     Conid 338719507 vs 559931429 2022-03-09  <>  2022-10-11

не одно ошибки 2021, а в 2022 тикеры с разными Conid десятки появились.
