### ISSUE TITLE
KeyError: 'Amount'

### ISSUE THREAD

**Issue by revic50** [cdump/investments#68]
Привет! С чем может быть связана такая ошибка:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\investments-master\investments\ibtax\__main__.py", line 3, in <module>
    main()
  File "D:\investments-master\investments\ibtax\ibtax.py", line 181, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\investments-master\investments\ibtax\ibtax.py", line 144, in parse_reports
    parser_object.parse_csv(
  File "D:\investments-master\investments\report_parsers\ib.py", line 201, in parse_csv
    self._real_parse_activity_csv(csv.reader(activity_fh, delimiter=','), {
  File "D:\investments-master\investments\report_parsers\ib.py", line 259, in _real_parse_activity_csv
    parser_fn(fields)
  File "D:\investments-master\investments\report_parsers\ib.py", line 355, in _parse_deposits
    amount = Money(f['Amount'], currency)
                   ~^^^^^^^^^^
KeyError: 'Amount'

**Comment by cdump** [comment]
Возможно отчет activity был выгружен не на английском языке

**Comment by revic50** [comment]
Точно, спасибо
