### ISSUE TITLE
ValueError: U.S. Treasury Bills

### ISSUE THREAD

**Issue by RaiaN** [cdump/investments#69]
Подгрузил все Activity Statement, получаю ошибку. В 2022 я покупал тикер BILL, не поддерживается?

В Activity statement имею следующую строчку:
```
Realized & Unrealized Performance Summary | Data | U.S. Treasury Bills | 912796ZM4 - United States Treasury B 01/31/23 | 0 | 0 | 0 | 0 | 0 | 0 | 50.64 | 0 | 0 | 0 | 50.64 | 50.64
```

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/raian/.local/lib/python3.10/site-packages/investments/ibtax/__main__.py", line 3, in <module>
    main()
  File "/home/raian/.local/lib/python3.10/site-packages/investments/ibtax/ibtax.py", line 181, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
  File "/home/raian/.local/lib/python3.10/site-packages/investments/ibtax/ibtax.py", line 144, in parse_reports
    parser_object.parse_csv(
  File "/home/raian/.local/lib/python3.10/site-packages/investments/report_parsers/ib.py", line 189, in parse_csv
    self._real_parse_activity_csv(csv.reader(ac_fh, delimiter=','), {
  File "/home/raian/.local/lib/python3.10/site-packages/investments/report_parsers/ib.py", line 259, in _real_parse_activity_csv
    parser_fn(fields)
  File "/home/raian/.local/lib/python3.10/site-packages/investments/report_parsers/ib.py", line 268, in _parse_instrument_information
    kind=_parse_tickerkind(f['Asset Category']),
  File "/home/raian/.local/lib/python3.10/site-packages/investments/report_parsers/ib.py", line 43, in _parse_tickerkind
    raise ValueError(strval)
ValueError: U.S. Treasury Bills

**Comment by cdump** [comment]
Не поддерживается, [тикет на поддержку bonds](https://github.com/cdump/investments/issues/13) (если это относится к Bonds)

У меня в портфеле такого нет, готов принять MR от знакомых с особенностями данного инструмента.
