### ISSUE TITLE
Ошибка при создании отчета 

### ISSUE THREAD

**Issue by eduard-takiullin** [cdump/investments#71]
Доброго всем времени суток!
Подскажите пожалуйста в чем моя ошибка.
При формировании отчета о движении денежных средств все работает, команды ввожу следующие:

cd /Users/Пользователь_2/Desktop/interactivebrokers/Activity/
python3 -m investments.ibdds --activity-report-filepath U3303333_2023.csv
Отчет работает

При формировании отчета по дивидендам ввожу следующую команду:

python3 -m investments.ibtax --activity-reports- /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ --confirmation-reports- /Users/ Пользователь_2/Desktop/interactivebrokers/Trade/

получаю следующее:

C:\Users\Пользователь_2>python3 -m investments.ibtax --activity-reports- /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ --confirmation-reports- /Users/ Пользователь_2/Desktop/interactivebrokers/Trade/
usage: __main__.py [-h] --activity-reports-dir ACTIVITY_REPORTS_DIR --confirmation-reports-dir
                   CONFIRMATION_REPORTS_DIR [--cache-dir CACHE_DIR] [--years YEARS] [--verbose [VERBOSE]]
                   [--quiet [QUIET]] [--report-type {native}] [--save-to SAVE_TO]
__main__.py: error: unrecognized arguments: Пользователь_2/Desktop/interactivebrokers/Trade/

**Comment by cdump** [comment]
@eduard-takiullin у вас лишний `-` в конце в `--activity-reports-`

**Comment by eduard-takiullin** [comment]
К сожалению не получается
C:\Users\Пользователь_2>python3 -m investments.ibtax --activity-reports /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ --confirmation-reports- /Users/ Пользователь_2/Desktop/interactivebrokers/Trade/

usage: __main__.py [-h] --activity-reports-dir ACTIVITY_REPORTS_DIR --confirmation-reports-dir
                   CONFIRMATION_REPORTS_DIR [--cache-dir CACHE_DIR] [--years YEARS] [--verbose [VERBOSE]]
                   [--quiet [QUIET]] [--report-type {native}] [--save-to SAVE_TO]
__main__.py: error: unrecognized arguments: Пользователь_2/Desktop/interactivebrokers/Trade/

**Comment by eduard-takiullin** [comment]
> @eduard-takiullinу вас лишний `-`в конце в`--activity-reports-`

Максим, не смогли бы Вы мне помочь написать правильную команду?

**Comment by cdump** [comment]
Теперь аналогичная ошибка в `--confirmation-reports-`

**Comment by eduard-takiullin** [comment]
C:\Users\Пользователь_2>python3 -m investments.ibtax --activity-reports dir /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ --confirmation-reports dir /Users/Пользователь_2/Desktop/interactivebrokers/Trade/

usage: __main__.py [-h] --activity-reports-dir ACTIVITY_REPORTS_DIR --confirmation-reports-dir
                   CONFIRMATION_REPORTS_DIR [--cache-dir CACHE_DIR] [--years YEARS] [--verbose [VERBOSE]]
                   [--quiet [QUIET]] [--report-type {native}] [--save-to SAVE_TO]
__main__.py: error: unrecognized arguments: /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ /Users/Пользователь_2/Desktop/interactivebrokers/Trade/

**Comment by eduard-takiullin** [comment]
C:\Users\Пользователь_2>python3 -m investments.ibtax --activity-reports-dir /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ --confirmation-reports-dir /Users/Пользователь_2/Desktop/interactivebrokers/Trade/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\ibtax\__main__.py", line 3, in <module>
    main()
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\ibtax\ibtax.py", line 175, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\ibtax\ibtax.py", line 138, in parse_reports
    parser_object.parse_csv(
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\report_parsers\ib.py", line 190, in parse_csv
    self._real_parse_activity_csv(
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\report_parsers\ib.py", line 250, in _real_parse_activity_csv
    for row in csv_reader:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 726: character maps to <undefined>

**Comment by cdump** [comment]
1. Вы открывали\редактировали сохранненные csv отчеты?
2. Вы выгружали их как в инструкции написано, на английском языке?

**Comment by eduard-takiullin** [comment]
1. Открывал но не редактировал
2. Да на английском.
3. Стоит еще раз выгрузить?
4.

**Comment by cdump** [comment]
Да, можно попробовать - там в ошибке что-то про cp1251 - это кодировка, мог редактор поменять на нее, я ожидал там ascii или utf-8.
Если не получится - это что-то с кодировкой и с windows связано, я с этим помочь разобраться не смогу.

**Comment by eduard-takiullin** [comment]
C:\Users\Пользователь_2\Desktop\interactivebrokers\Activity>python3 -m investments.ibtax --activity-reports-dir /Users/Пользователь_2/Desktop/interactivebrokers/Activity/ --confirmation-reports-dir /Users/Пользователь_2/Desktop/interactivebrokers/Trade/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\ibtax\__main__.py", line 3, in <module>
    main()
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\ibtax\ibtax.py", line 175, in main
    parser_object = parse_reports(args.activity_reports_dir, args.confirmation_reports_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\ibtax\ibtax.py", line 138, in parse_reports
    parser_object.parse_csv(
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\report_parsers\ib.py", line 190, in parse_csv
    self._real_parse_activity_csv(
  File "C:\Users\Пользователь_2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\investments\report_parsers\ib.py", line 250, in _real_parse_activity_csv
    for row in csv_reader:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 726: character maps to <undefined>
Это с новым отчетом.
